# Generated by Django 3.1.1 on 2020-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_competency',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
