# Generated by Django 3.1.1 on 2020-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='ql_b',
            field=models.FloatField(default=0),
        ),
    ]
