# Generated by Django 3.1.1 on 2020-09-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='c_prob',
        ),
    ]
