# Generated by Django 3.1.1 on 2020-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizlog_ql_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='ql_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quizlog',
            name='questionlog',
            field=models.IntegerField(default=0),
        ),
    ]
