# Generated by Django 3.1.1 on 2020-11-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='sclog',
            field=models.IntegerField(default=0),
        ),
    ]
