# Generated by Django 3.1.1 on 2020-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizlog_sclog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
