# Generated by Django 3.1.1 on 2020-11-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201122_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Jawaban Pertanyaan', 'verbose_name_plural': 'Jawaban Pertanyaan'},
        ),
        migrations.AlterModelOptions(
            name='base_competency',
            options={'verbose_name': 'Kompetensi Dasar', 'verbose_name_plural': 'Kompetensi Dasar'},
        ),
        migrations.AlterModelOptions(
            name='core_competency',
            options={'verbose_name': 'Kompetensi Inti', 'verbose_name_plural': 'Kompetensi Inti'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pertanyaan', 'verbose_name_plural': 'Pertanyaan'},
        ),
        migrations.AlterModelOptions(
            name='quiztaker',
            options={'verbose_name': 'Pengambil Kuis', 'verbose_name_plural': 'Pengambil Kuis'},
        ),
        migrations.AlterModelOptions(
            name='scoredetil',
            options={'verbose_name': 'Skor per Indikator', 'verbose_name_plural': 'Skor per Indikator'},
        ),
        migrations.AlterModelOptions(
            name='specific_competency',
            options={'ordering': ['timestamp'], 'verbose_name': 'Indikator', 'verbose_name_plural': 'Indikator'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Mata Pelajaran', 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topik', 'verbose_name_plural': 'Topik'},
        ),
        migrations.AlterModelOptions(
            name='usersanswer',
            options={'verbose_name': 'Jawaban Pengguna', 'verbose_name_plural': 'Jawaban Pengguna'},
        ),
    ]
