# Generated by Django 3.1.1 on 2020-12-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specific_competency',
            options={'verbose_name': 'Indikator', 'verbose_name_plural': 'Indikator'},
        ),
        migrations.RemoveField(
            model_name='specific_competency',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='question',
        ),
        migrations.AlterField(
            model_name='core_competency',
            name='classes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
