# Generated by Django 3.1.1 on 2020-12-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201202_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_competency',
            name='roll_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='base_competency',
            name='ability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specific_competency',
            name='description',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
