# Generated by Django 3.1.1 on 2020-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201207_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_competency',
            name='ability',
        ),
        migrations.AddField(
            model_name='base_competency',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=400),
        ),
    ]
