# Generated by Django 3.1.1 on 2020-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20201217_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetil',
            name='desc',
            field=models.FloatField(default=0),
        ),
    ]
