# Generated by Django 3.1.1 on 2020-12-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20201217_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='nebak',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersanswer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
