# Generated by Django 3.1.1 on 2020-11-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.CharField(default=3, max_length=100, verbose_name='kelas'),
            preserve_default=False,
        ),
    ]
