# Generated by Django 3.1.1 on 2020-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.CharField(default=None, max_length=100, verbose_name='kelas'),
        ),
    ]
