# Generated by Django 3.1.1 on 2020-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201130_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sekolah',
            field=models.CharField(blank=True, max_length=100, verbose_name='sekolah'),
        ),
    ]
